package com.rcore.model;

import com.rcore.global.bcomponent.base.ApplicationModuleImplRcore;
import com.rcore.global.bcomponent.base.ViewObjectImplRcore;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 23 10:24:01 MSK 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends ApplicationModuleImplRcore
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
    super();
  }

  /**
   * Container's getter for TCityView1.
   * @return TCityView1
   */
  public ViewObjectImplRcore getTCityView1()
  {
    return (ViewObjectImplRcore) findViewObject("TCityView1");
  }

  /**
   * Container's getter for TCountryView1.
   * @return TCountryView1
   */
  public ViewObjectImplRcore getTCountryView1()
  {
    return (ViewObjectImplRcore) findViewObject("TCountryView1");
  }

  /**
   * Container's getter for THouseView1.
   * @return THouseView1
   */
  public ViewObjectImplRcore getTHouseView1()
  {
    return (ViewObjectImplRcore) findViewObject("THouseView1");
  }

  /**
   * Container's getter for TRegionView1.
   * @return TRegionView1
   */
  public ViewObjectImplRcore getTRegionView1()
  {
    return (ViewObjectImplRcore) findViewObject("TRegionView1");
  }

  /**
   * Container's getter for TStreetView1.
   * @return TStreetView1
   */
  public ViewObjectImplRcore getTStreetView1()
  {
    return (ViewObjectImplRcore) findViewObject("TStreetView1");
  }

  /**
   * Container's getter for TCityView2.
   * @return TCityView2
   */
  public ViewObjectImplRcore getTCityView2()
  {
    return (ViewObjectImplRcore) findViewObject("TCityView2");
  }

  /**
   * Container's getter for TRegionView2.
   * @return TRegionView2
   */
  public ViewObjectImplRcore getTRegionView2()
  {
    return (ViewObjectImplRcore) findViewObject("TRegionView2");
  }

  /**
   * Container's getter for THouseView2.
   * @return THouseView2
   */
  public ViewObjectImplRcore getTHouseView2()
  {
    return (ViewObjectImplRcore) findViewObject("THouseView2");
  }

  /**
   * Container's getter for TStreetView2.
   * @return TStreetView2
   */
  public ViewObjectImplRcore getTStreetView2()
  {
    return (ViewObjectImplRcore) findViewObject("TStreetView2");
  }

  /**
   * Container's getter for TCityRegionLink1.
   * @return TCityRegionLink1
   */
  public ViewLinkImpl getTCityRegionLink1()
  {
    return (ViewLinkImpl) findViewLink("TCityRegionLink1");
  }

  /**
   * Container's getter for TRegionCountryLink1.
   * @return TRegionCountryLink1
   */
  public ViewLinkImpl getTRegionCountryLink1()
  {
    return (ViewLinkImpl) findViewLink("TRegionCountryLink1");
  }

  /**
   * Container's getter for THouseStreetLink1.
   * @return THouseStreetLink1
   */
  public ViewLinkImpl getTHouseStreetLink1()
  {
    return (ViewLinkImpl) findViewLink("THouseStreetLink1");
  }

  /**
   * Container's getter for TStreetCityLink1.
   * @return TStreetCityLink1
   */
  public ViewLinkImpl getTStreetCityLink1()
  {
    return (ViewLinkImpl) findViewLink("TStreetCityLink1");
  }

  /**
   * Container's getter for ViewObjTest1.
   * @return ViewObjTest1
   */
  public ViewObjectImpl getViewObjTest1()
  {
    return (ViewObjectImpl) findViewObject("ViewObjTest1");
  }
}
