package com.rcore.model;

import com.rcore.global.bcomponent.base.ViewObjectImplRcore;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 23 10:30:23 MSK 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TCountryViewImpl  extends ViewObjectImplRcore
{
  /**
   * This is the default constructor (do not remove).
   */
  public TCountryViewImpl()
  {
    super();
  }

  /**
   * Returns the bind variable value for country.
   * @return bind variable value for country
   */
  public String getcountry()
  {
    return (String) getNamedWhereClauseParam("country");
  }

  /**
   * Sets <code>value</code> for bind variable country.
   * @param value value to bind as country
   */
  public void setcountry(String value)
  {
    setNamedWhereClauseParam("country", value);
  }
}
