package com.rcore.model;

import com.rcore.global.bcomponent.base.ViewObjectImplRcore;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 23 10:28:58 MSK 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TRegionViewImpl
  extends ViewObjectImplRcore
{
  /**
   * This is the default constructor (do not remove).
   */
  public TRegionViewImpl()
  {
  }
}
