package com.rcore.model;

import com.rcore.global.bcomponent.base.EntityImplRcore;
import com.rcore.global.bcomponent.base.ViewRowImplRcore;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 23 10:29:18 MSK 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TStreetViewRowImpl
  extends ViewRowImplRcore
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum
  {
    StreetId
    {
      public Object get(TStreetViewRowImpl obj)
      {
        return obj.getStreetId();
      }

      public void put(TStreetViewRowImpl obj, Object value)
      {
        obj.setStreetId((Number)value);
      }
    }
    ,
    CityId
    {
      public Object get(TStreetViewRowImpl obj)
      {
        return obj.getCityId();
      }

      public void put(TStreetViewRowImpl obj, Object value)
      {
        obj.setCityId((Number)value);
      }
    }
    ,
    Sname
    {
      public Object get(TStreetViewRowImpl obj)
      {
        return obj.getSname();
      }

      public void put(TStreetViewRowImpl obj, Object value)
      {
        obj.setSname((String)value);
      }
    }
    ,
    THouseView
    {
      public Object get(TStreetViewRowImpl obj)
      {
        return obj.getTHouseView();
      }

      public void put(TStreetViewRowImpl obj, Object value)
      {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(TStreetViewRowImpl object);

    public abstract void put(TStreetViewRowImpl object, Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int STREETID = AttributesEnum.StreetId.index();
  public static final int CITYID = AttributesEnum.CityId.index();
  public static final int SNAME = AttributesEnum.Sname.index();
  public static final int THOUSEVIEW = AttributesEnum.THouseView.index();

  /**
   * This is the default constructor (do not remove).
   */
  public TStreetViewRowImpl()
  {
  }

  /**
   * Gets TStreet entity object.
   * @return the TStreet
   */
  public EntityImplRcore getTStreet()
  {
    return (EntityImplRcore) getEntity(0);
  }

  /**
   * Gets the attribute value for STREET_ID using the alias name StreetId.
   * @return the STREET_ID
   */
  public Number getStreetId()
  {
    return (Number) getAttributeInternal(STREETID);
  }

  /**
   * Sets <code>value</code> as attribute value for STREET_ID using the alias name StreetId.
   * @param value value to set the STREET_ID
   */
  public void setStreetId(Number value)
  {
    setAttributeInternal(STREETID, value);
  }

  /**
   * Gets the attribute value for CITY_ID using the alias name CityId.
   * @return the CITY_ID
   */
  public Number getCityId()
  {
    return (Number) getAttributeInternal(CITYID);
  }

  /**
   * Sets <code>value</code> as attribute value for CITY_ID using the alias name CityId.
   * @param value value to set the CITY_ID
   */
  public void setCityId(Number value)
  {
    setAttributeInternal(CITYID, value);
  }

  /**
   * Gets the attribute value for SNAME using the alias name Sname.
   * @return the SNAME
   */
  public String getSname()
  {
    return (String) getAttributeInternal(SNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for SNAME using the alias name Sname.
   * @param value value to set the SNAME
   */
  public void setSname(String value)
  {
    setAttributeInternal(SNAME, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link THouseView.
   */
  public RowIterator getTHouseView()
  {
    return (RowIterator) getAttributeInternal(THOUSEVIEW);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
